### PR TITLE
New program is added. (Squash and merge this into a single commit)

### PR DESCRIPTION
**Pull request by Sid672**
Please review it.

### CODE REVIEW

**Comment by shivesh01** [comment]
Try to put it in md file which looks better...

**Comment by Sid672** [comment]
It is more time taken if we put code in README.md. But I can add comments to this program.

**Comment by Sid672** [comment]
@shivesh01, Ok now I understand README.md looks better. I am updating it.

**Comment by shivesh01** [comment]
Nice work!

**Pull request merged**
